### PR TITLE
Add methods to get sorted column & direction,  and sort by column & direction. 

### PR DESCRIPTION
**Pull request by long-greg-c**
@ISchwarz23 Firstly thanks for creating this library.
I have added some functionality I needed, appreciate if you have the time to review.

The new methods can be used to obtain the current sort state, this info can then be persisted across fragment/activity lifecycle changes. 
The sorted table can then be re-sorted after a fragment/activity resume.

### CODE REVIEW

**Comment by ISchwarz23** [comment]
@long-greg-c Thank you for helping making this library more mature. It would be great, if you could add javadoc to the added methods.

Best Regards,
Ingo

**Comment by ISchwarz23** [comment]
Or I think it would be cleaner if we implement the onSaveInstanceState and onRestoreInstanceState of the base class `View`.

See an example at: http://stackoverflow.com/a/8127813/5031358

It would simplify the usage of the Table, as the developer does not need to know which attributes need to be saved. @long-greg-c 
What do you think?

**Comment by ISchwarz23** [comment]
As described above I decided to add this functionality in the "standard Android way". The TableView as well as the SortableTableview are now able to persist their state without any action required by the developer. This feature is available since the version `1.1.0`.  
If you do not want your table to keep its state you can do so by calling the `setSaveEnabled(boolean enabled)` passing `false`.

**Comment by long-greg-c** [comment]
Thanks for adding the state persistence functionality. the way you implemented it is nice, I appreciate you suggesting the alternative and taking the time to implement it.

**Comment by ISchwarz23** [comment]
Thanks for reporting the missing feature! :)

**Pull request closed without merging**
